char* creatures[2789] = {
	"Aarakocra",
	"Aasimar",
	"Aballin",
	"Abeil",
	"Queen Abeil",
	"Soldier Abeil",
	"Vassal Abeil",
	"Black  Abishai",
	"Blue  Abishai",
	"Green  Abishai",
	"Red  Abishai",
	"White  Abishai",
	"Aboleth",
	"Aboleth Mage",
	"Psionic Aboleth",
	"Anaxim Abomination",
	"Attropal Abomination",
	"Chichimec Abomination",
	"Dream Larva Abomination",
	"Hecatoncheires Abomination",
	"Infernal Abomination",
	"Phaethon Abomination",
	"Phane Abomination",
	"Xixecal Abomination",
	"Abrian",
	"Abyssal Eviscerator",
	"Abyssal Maw",
	"Abyssal Ravager",
	"Abyssal Stalker",
	"Achaierai",
	"Adverspa",
	"Ahuitzol",
	"Alaghi",
	"Albatross",
	"Aleax",
	"Alkilith",
	"All-Consuming Hunger",
	"Allip",
	"Ambush Drake",
	"Amnizu",
	"Amphibious Creature",
	"Amphisbaena",
	"Anarchic Creature",
	"Anarchic Creature",
	"Ancient Night Twist",
	"Androsphinx",
	"Angel",
	"Angel of Decay",
	"Anguillian",
	"Arctic Animal",
	"Dire Animal",
	"Animated Object",
	"Colossal Animated Object",
	"Gargantuan Animated Object",
	"Huge Animated Object",
	"Large Animated Object",
	"Medium Animated Object",
	"Small Animated Object",
	"Tiny Animated Object",
	"Animated Rug of Welcome",
	"Ankheg",
	"Annihilator",
	"Giant Ant Lion",
	"Giant Ant",
	"Giant Queen Ant",
	"Giant Soldier Ant",
	"Giant Worker Ant",
	"Anthropomorphic Animal",
	"Droplet Aoa",
	"Sphere Aoa",
	"Ape",
	"Dire Ape",
	"Legendary Ape",
	"Arachnoid Creature",
	"Arachnoid Creature",
	"Aranea",
	"Homunculus Arbalester",
	"Archon",
	"Archon",
	"Hammer Archon",
	"Hound Archon",
	"Hound Hero Archon",
	"Lantern Archon",
	"Owl Archon",
	"Sword Archon",
	"Throne Archon",
	"Trumpet Archon",
	"Warden Archon",
	"Word Archon",
	"Armand",
	"Armand Warden",
	"Demon  Armanite",
	"Arrowhawk",
	"Adult Arrowhawk",
	"Elder Arrowhawk",
	"Juvenile Arrowhawk",
	"Artaaglith",
	"Asabi",
	"Ascendant Councilor",
	"Ash Rat",
	"Ashen Husk",
	"Asherati",
	"Ashworm",
	"Aspect of Asmodeus",
	"Aspect of Bahamut",
	"Aspect of Demogorgon",
	"Aspect of Hextor",
	"Aspect of Kord",
	"Aspect of Lolth",
	"Aspect of Mephistopheles",
	"Aspect of Nerull",
	"Aspect of Orcus",
	"Aspect of Tiamat",
	"Aspect of Vecna",
	"Asperi",
	"Assassin Vine",
	"Astral Construct",
	"Astral Deva",
	"Astral Dreadnought",
	"Astral Kraken",
	"Astral Stalker",
	"Asura",
	"Athach",
	"Atropal Scion",
	"Automaton",
	"Hammerer Automaton",
	"Pulverizer Automaton",
	"Avalancher",
	"Aventi",
	"Aventi Sergeant",
	"Avolakia",
	"Axiomatic Creature",
	"Axiomatic Creature",
	"Axiomatic Creature",
	"Azer",
	"Azurin",
	"Babau",
	"Babau",
	"Baboon",
	"Bacchae",
	"Badger",
	"Dire Badger",
	"the Platinum Dragon Bahamut",
	"Bajang",
	"Bakemono",
	"Baleen Whale",
	"Bane Wraith",
	"Banedead",
	"Baneguard",
	"Baneguard",
	"Banelar",
	"Banshee",
	"Baphitaur",
	"Barbed Devil",
	"Barghest",
	"Greater Barghest",
	"Greater Barghest",
	"Bariaur",
	"Bariaur",
	"Defender of Ysgard Bariaur",
	"Bar-lgura",
	"Barracuda",
	"Dire Barracuda",
	"Basilisk",
	"Abyssal Greater Basilisk",
	"Bat",
	"Desmodu Bat",
	"Desmodu Guard Bat",
	"Desmodu War Bat",
	"Dire Bat",
	"Fire Bat",
	"Guard Bat",
	"Hunting Bat",
	"War Bat",
	"Battle Effigy",
	"Battle Horror",
	"Battlebriar",
	"the Firebringer Bazim-Gorag",
	"Black Bear",
	"Brown Bear",
	"Dire Bear",
	"Legendary Bear",
	"Legendary Bear",
	"Polar Bear",
	"Bearded Devil",
	"Bearhound",
	"Beast of Malar",
	"Beast of Xvim",
	"Bebilith",
	"Giant Bee",
	"Devastation Beetle",
	"Giant Bombadier Beetle",
	"Giant Fire Beetle",
	"Giant Stag Beetle",
	"Knell Beetle",
	"Knell Lesser Beetle",
	"Beguiler",
	"Behemoth",
	"Eagle Behemoth",
	"Gorilla Behemoth",
	"Behir",
	"Halruaan Behir",
	"Beholder",
	"Death Tyrant Beholder",
	"Gauth Beholder",
	"Beholderkin",
	"Death Kiss Beholderkin",
	"Director Beholderkin",
	"Eye of the Deep Beholderkin",
	"Eyeball Beholderkin",
	"Gouger Beholderkin",
	"Hive Mother Beholderkin",
	"Overseer Beholderkin",
	"Spectator Beholderkin",
	"Spectator Beholderkin",
	"Belker",
	"Bheur",
	"Bhuka",
	"Bhut",
	"Bisan",
	"Bison",
	"Black Pudding",
	"Elder Black Pudding",
	"Blackskate",
	"Blackstone Gigant",
	"Blade Guardian",
	"Blade Spirit",
	"Bladeling",
	"Blaspheme",
	"Bleakborn",
	"Blightspawned",
	"Blink Dog",
	"Blood Amniote",
	"Blood Ape",
	"Blood Fiend",
	"Blood Hawk",
	"Bloodbloater",
	"Blooded One",
	"Bloodmote Cloud",
	"Bloodrot",
	"Bloodthorn",
	"Blue",
	"Boar",
	"Dire Boar",
	"Razor Boar",
	"Bodak",
	"Bog Hag",
	"Bog Imp",
	"Boggle",
	"Bogun",
	"Bogun",
	"Bogun",
	"Bone Creature",
	"Bone Devil",
	"Bonebat",
	"Boneclaw",
	"Bonedrinker",
	"Lesser Bonedrinker",
	"Boneleaf",
	"Bonesinger",
	"Bonespear",
	"Boneyard",
	"Brachyurus",
	"Brain in a Jar",
	"Brain Mole",
	"Bralani",
	"Branta",
	"Branta",
	"Brass Steed",
	"Braxat",
	"Breathdrinker",
	"Breed Leech",
	"Bright Naga",
	"Brine Swimmer",
	"Brixashulty",
	"Bronze Serpent",
	"Brood Keeper",
	"Bugbear",
	"Bulette",
	"Bullywug",
	"Burning Skeleton",
	"Tigbanua Buso",
	"Cachalot Whale",
	"Cadavar Collector",
	"Greater Cadavar Collector",
	"Caller from the Deeps",
	"Caller in Darkness",
	"Camel",
	"Dromedary Camel",
	"Two-Humped Camel",
	"War Camel",
	"Camelopardel",
	"Yugoloth Canoloth",
	"Canomorph",
	"Captured One",
	"Carcass Crab",
	"Carcass Eater",
	"Caribou",
	"Carrion Crawler",
	"Caryatid Column",
	"Cat",
	"Sea Cat",
	"Catfolk",
	"Catoblepas",
	"Cavvekan",
	"Celestial",
	"Celestial Creature",
	"Centaur",
	"Least Spirit Centipede",
	"Lesser Spirit Centipede",
	"Monstrous Centipede",
	"Small Spirit Centipede",
	"Century Worm",
	"Ceratosaur",
	"Cerebrilith",
	"Cervidal",
	"Elemental Grue Chaggrin",
	"Chain Devil",
	"Chameleon Creature",
	"Changeling",
	"Chaos Beast",
	"Chaos Roc",
	"Charnel Hound",
	"Chasme",
	"Cheetah",
	"Chekryan",
	"Chelicera",
	"Chiang Lung",
	"Chilblain",
	"Chilling Fog",
	"Chimera",
	"Chimeric Creature",
	"Chitine",
	"Choker",
	"Shadow Choker",
	"Choldrith",
	"Chordevoc",
	"Chosen One",
	"Chraal",
	"Chronotyryn",
	"Chuul",
	"Chwidencha",
	"Cildabrin",
	"Cinderspawn",
	"Climbdog",
	"Cloaked Ape",
	"Cloaker",
	"Cloaker Lord",
	"Shadowcloak Elder Cloaker",
	"Shadowcloak Elder Cloaker",
	"Clockwork Horror",
	"Cloud Ray",
	"Cockatrice",
	"Giant Cockroach",
	"Colossus",
	"Flesh Colossus",
	"Iron Colossus",
	"Stone Colossus",
	"Constrictor Snake",
	"Giant Constrictor Snake",
	"Corollax",
	"Corpse Creature",
	"Corpse Gatherer",
	"Corrupted Cretaure",
	"Corruption Eater",
	"Couatl",
	"Psionic Couatl",
	"Monstrous Crab",
	"Crawling Apocalypse",
	"Crawling Claw",
	"Crawling Claw",
	"Crawling Gauntlet",
	"Crawling Head",
	"Crimson Death",
	"Criosphinx",
	"Crocodile",
	"Giant Crocodile",
	"Crossroads Guardian",
	"Crucian",
	"Crucian",
	"Cryohydra",
	"Crypt Chanter",
	"Crypt Spawn",
	"Crypt Thing",
	"Crypt Warden",
	"Crysmal",
	"Crystal Screamer",
	"Cursed Cold One",
	"Cursed Spirit",
	"Curst",
	"Curst",
	"Giant Cyclops",
	"Greater Cyclops",
	"Lesser Cyclops",
	"Daelkyr",
	"Darfellan",
	"Darfellen Barbarian",
	"Dark Creature",
	"Dark Creeper",
	"Dark Ones",
	"Dark Stalker",
	"Dark Tree",
	"Dark Tree",
	"Darkenbeast",
	"Darkmantle",
	"Darktentacles",
	"Darkweaver",
	"Deadly Dancer",
	"Death Dog",
	"Death Knight",
	"Death Knight",
	"Deathbringer",
	"Deathcoils",
	"Deathfang",
	"Deathlock",
	"Deathshead",
	"Deathshrieker",
	"Advanced Deathshrieker",
	"Deep Hound",
	"Deepspawn",
	"Deepspawn",
	"Deer",
	"Delver",
	"Demilich",
	"Demodand",
	"Demon",
	"Demon",
	"Demon",
	"Arrow Demon",
	"Balor Demon",
	"Blood Fiend Demon",
	"Ghour Demon",
	"Ghour Demon",
	"Maurezhi  Demon",
	"Sorrowsworn Demon",
	"Yochlol Demon",
	"Dendar the Night Serpent",
	"Derro",
	"Desert Devil",
	"Desiccator",
	"Desmodu",
	"Desmodu",
	"Desmodu",
	"Destrachan",
	"Deva",
	"Monadic Deva",
	"Devastation Centipede",
	"Devastation Vermin",
	"Scorpion Devastation",
	"Devil",
	"Devil",
	"Devil",
	"Logokron Devil",
	"Devourer",
	"Dharculus",
	"Digester",
	"Dinosaur",
	"Dinosaur",
	"Dinosaur",
	"Allosaurus Dinosaur",
	"Ankylosaurus Dinosaur",
	"Archelon Dinosaur",
	"Battletitan Dinosaur",
	"Bloodstriker Dinosaur",
	"Cave Ankylosaurus Dinosaur",
	"Cave Triceratops Dinosaur",
	"Cave Tyrannosaurus Dinosaur",
	"Clawfoot Dinosaur",
	"Cryptoclidus Dinosaur",
	"Deinonychus Dinosaur",
	"Diprotodon Dinosaur",
	"Elasmosaurus Dinosaur",
	"Fastieth Dinosaur",
	"Fleshraker Dinosaur",
	"Glidewing Dinosaur",
	"Icthyosaur Dinosaur",
	"Megaraptor Dinosaur",
	"Mosasaur Dinosaur",
	"Pleiosaur Dinosaur",
	"Protoceratops Dinosaur",
	"Quetzalcoatlus Dinosaur",
	"Seismosaurus Dinosaur",
	"Spinosaurus Dinosaur",
	"Swindlespitter Dinosaur",
	"Triceratops Dinosaur",
	"Tyrannosaurus Dinosaur",
	"Dire Animal",
	"Dire Animal",
	"Dire Animal",
	"Direguard",
	"Disenchanter",
	"Displacer Beast",
	"Pack Lord Displacer Beast",
	"Displacer Serpent",
	"Djinni",
	"Noble Djinni",
	"Doc Cu'o'c",
	"Dog",
	"Riding Dog",
	"Dokufu",
	"Dolgaunt",
	"Dolghast",
	"Dolgrim",
	"Domovoi",
	"Donkey",
	"Doppelganger",
	"Greater Doppelganger",
	"Doppleganger",
	"Dracolich",
	"Dracolich",
	"Ancient Blue Dracolich",
	"Aurak Draconian",
	"Baaz Draconian",
	"Bozak Draconian",
	"Kapak Draconian",
	"Sivak Draconian",
	"Draconic Creature",
	"Draconic Creature",
	"Dracotaur",
	"Dracotaur Rager",
	"Half-Fiend Draegloth",
	"Dragon Eel",
	"Dragon Turtle",
	"Advanced Dragon",
	"Amethyst Dragon",
	"Battle  Dragon",
	"Black Dragon",
	"Blue Dragon",
	"Brass Dragon",
	"Bronze Dragon",
	"Brown Dragon",
	"Chaos  Dragon",
	"Chromatic Dragon",
	"Copper Dragon",
	"Crystal Dragon",
	"Deep Dragon",
	"Emerald Dragon",
	"Epic Dragon",
	"Epic Force Dragon",
	"Epic Prismatic Dragon",
	"Ethereal  Dragon",
	"Faerie Dragon",
	"Fang Dragon",
	"Fang Dragon",
	"Gem Dragon",
	"Ghostly Dragon",
	"Ghostly Adult Green Dragon",
	"Gold Dragon",
	"Green Dragon",
	"Howling  Dragon",
	"Incarnum Dragon",
	"Metallic Dragon",
	"Oceanus  Dragon",
	"Planar Dragon",
	"Pyroclastic  Dragon",
	"Radiant  Dragon",
	"Rattelyr Dragon",
	"Red Dragon",
	"Rust  Dragon",
	"Sand Dragon",
	"Sapphire Dragon",
	"Shadow Dragon",
	"Shadow Dragon",
	"Silver Dragon",
	"Skeletal Dragon",
	"Skeletal Mature Adult Black Dragon",
	"Song Dragon",
	"Spiretop Dragon",
	"Styx  Dragon",
	"Tarterian  Dragon",
	"Topaz Dragon",
	"True Dragon",
	"Vampiric Dragon",
	"Vampiric Mature Adult Red Dragon",
	"White Dragon",
	"Zombie Dragon",
	"Zombie Young Adult Whitye Dragon",
	"Dragonborn of Bahamut",
	"Giant Dragonfly",
	"Dragonkin",
	"Dragonkin",
	"Dragonne",
	"Dragonnel",
	"Dragonspawn",
	"Abyssal Drake",
	"Air Drake",
	"Earth Drake",
	"Elemental Drake",
	"Fire Drake",
	"Ice Drake",
	"Magma Drake",
	"Ooze Drake",
	"Sea Drake",
	"Smoke Drake",
	"Stone Drake",
	"Storm Drake",
	"Water Drake",
	"Dread",
	"Dread Guard",
	"Dread Ram",
	"Dread Warrior",
	"Dread Warrior",
	"Dread Warrior",
	"Dread Wraith",
	"Dream Vestige",
	"Dretch",
	"Drider",
	"Drider Vampire",
	"Dromite",
	"Drowned",
	"Dryad",
	"Dune Stalker",
	"Dunewinder",
	"Ephemera Dusk Beast",
	"Duskling",
	"Dust Twister",
	"Dustblight",
	"Dustform Creature",
	"Dust-Stuffed",
	"Dwarf",
	"Dwarf Einherjar",
	"Deep Dwarf",
	"Dream  Dwarf",
	"Duergar Dwarf",
	"Duergar Psionic Dwarf",
	"Faerunian Dwarf",
	"Frost Dwarf",
	"Glacier Dwarf",
	"Glacier Snow Hunter Dwarf",
	"Midgard Dwarf",
	"Mountain Dwarf",
	"Dweomervore",
	"Eagle",
	"Dire Eagle",
	"Giant Eagle",
	"Giant Eagle",
	"Legendary Eagle",
	"Earth Glider",
	"Earth Whisper",
	"Ephemera Ecalypse",
	"Ectoplasmic Vermin",
	"Eel",
	"Dire Eel",
	"Effigy",
	"Effigy Creature",
	"Efreeti",
	"Elder Eidolon",
	"Eladrin",
	"Eladrin",
	"Coure Eladrin",
	"Firre Eladrin",
	"Shiradi Eladrin",
	"Tulani Eladrin",
	"Elan",
	"Elder Brain",
	"Elder Brain",
	"Psionic Elder Brain",
	"Element Creature",
	"Elemental",
	"Elemental Weird",
	"Elemental Weird",
	"Ice Elemental Weird",
	"Snow Elemental Weird",
	"Air Elemental",
	"Air Primal Elemental",
	"Earth Elemental",
	"Earth Primal Elemental",
	"Elder Shadow Elemental",
	"Fire Elemental",
	"Fire Primal Elemental",
	"Greater Shadow Elemental",
	"Huge Shadow Elemental",
	"Large Shadow Elemental",
	"Medium Shadow Elemental",
	"Primal Elemental",
	"Small Shadow Elemental",
	"Storm Elemental",
	"Water Elemental",
	"Water Primal Elemental",
	"Elephant",
	"Dire Elephant",
	"Dire Elephant",
	"Elf",
	"Aquatic Elf",
	"Aquatic Elf",
	"Aquatic Dolphin Rider Elf",
	"Drow Elf",
	"Einherjar Elf",
	"Gray Elf",
	"Wild Elf",
	"Wood Elf",
	"Elite Demon War Mount",
	"Elk",
	"Dire Elk",
	"Dire Elk",
	"Elsewhale",
	"Lord of the Hidden Layer Eltab",
	"Elven Hound",
	"Elysian Thrush",
	"Xac-Yel Energon",
	"Xac-Yij Energon",
	"Xag-Ya Energon",
	"Xap-Yaup Energon",
	"Xeg-Yi Energon",
	"Xong-Yong Energon",
	"Xor-Yost Energon",
	"Entombed",
	"Entomber",
	"Entropic Creature",
	"Entropic Reaper",
	"Ephemeral Hangman",
	"Equiceph",
	"Amphail Gray Equine",
	"Calimite Equine",
	"Chionthar Equine",
	"Cormyrean Destrier Equine",
	"Dales Pony Equine",
	"Dambraii Equine",
	"Hammer Pony Equine",
	"Island Pony Equine",
	"Kromlor Equine",
	"Lhesperan Equine",
	"Meth Equine",
	"Nars Equine",
	"Raurin Equine",
	"Semphari Equine",
	"Shaaran Zebra Equine",
	"Shad'iar Equine",
	"Sosser Equine",
	"Steppe Equine",
	"Tharurr Equine",
	"Uglib Equine",
	"Whiteshield Equine",
	"Erinyes",
	"Ether Scarab",
	"Ethereal Doppleganger",
	"Ethereal Filcher",
	"Ethereal Marauder",
	"Ethereal Slayer",
	"Ethergaunt",
	"Black Ethergaunt",
	"Red Ethergaunt",
	"White Ethergaunt",
	"Ettercap",
	"Ettin",
	"Evolved Undead",
	"Eye of Fear and Flame",
	"Faerunian Ha-Naga",
	"Faerzress-Infused Creature",
	"Famine Spirit",
	"Farastu",
	"Faun",
	"Felldrake",
	"Crested Felldrake",
	"Horned Felldrake",
	"Spiked Felldrake",
	"Spitting Felldrake",
	"Fensir",
	"Feral Spirit",
	"Feral Yowler",
	"Fetch",
	"Fey'ri",
	"Feytouched",
	"Fhorge",
	"Fiendish Creature",
	"Fiendwurm",
	"Fihyr",
	"Greater Fihyr",
	"Firbolg",
	"Giant Firefly",
	"Firenewt",
	"Fireshadow",
	"Celestial  Firre",
	"Greater Flame Snake",
	"Lesser Flame Snake",
	"Minor Flame Snake",
	"Flameskull",
	"Flesh Jelly",
	"Folugub",
	"Fomorian",
	"Forest Sloth",
	"Forgewraith",
	"Forlorn Husk",
	"Formarian",
	"Armadon Formarian",
	"Observer Formarian",
	"Winged Warrior Formarian",
	"Formian",
	"Formian Myrmarch",
	"Formian Queen",
	"Formian Taskmaster",
	"Formian Warrior",
	"Formian Worker",
	"Forsaken Shell",
	"Fossergrim",
	"Foulwing",
	"Arctic Fox",
	"Giant Frog",
	"Frost Folk",
	"Frost Giant Jarl",
	"Jotunheim Frost Giant",
	"Frost Salamander",
	"Frost Worm",
	"Fungus",
	"Galeb Duhr",
	"Gambol",
	"Garbler",
	"Gargoyle",
	"Kir-Lanan Gargoyle",
	"Feral  Gargun",
	"Gas Spore",
	"Xac-Yij Energon",
	"Xag-Ya Energon",
	"Xap-Yaup Energon",
	"Xeg-Yi Energon",
	"Xong-Yong Energon",
	"Xor-Yost Energon",
	"Entombed",
	"Entomber",
	"Entropic Creature",
	"Entropic Reaper",
	"Ephemeral Hangman",
	"Equiceph",
	"Amphail Gray Equine",
	"Calimite Equine",
	"Chionthar Equine",
	"Cormyrean Destrier Equine",
	"Dales Pony Equine",
	"Dambraii Equine",
	"Hammer Pony Equine",
	"Island Pony Equine",
	"Kromlor Equine",
	"Lhesperan Equine",
	"Meth Equine",
	"Nars Equine",
	"Raurin Equine",
	"Semphari Equine",
	"Shaaran Zebra Equine",
	"Shad'iar Equine",
	"Sosser Equine",
	"Steppe Equine",
	"Tharurr Equine",
	"Uglib Equine",
	"Whiteshield Equine",
	"Erinyes",
	"Ether Scarab",
	"Ethereal Doppleganger",
	"Ethereal Filcher",
	"Ethereal Marauder",
	"Ethereal Slayer",
	"Ethergaunt",
	"Black Ethergaunt",
	"Red Ethergaunt",
	"White Ethergaunt",
	"Ettercap",
	"Ettin",
	"Evolved Undead",
	"Eye of Fear and Flame",
	"Faerunian Ha-Naga",
	"Faerzress-Infused Creature",
	"Famine Spirit",
	"Farastu",
	"Faun",
	"Felldrake",
	"Crested Felldrake",
	"Horned Felldrake",
	"Spiked Felldrake",
	"Spitting Felldrake",
	"Fensir",
	"Feral Spirit",
	"Feral Yowler",
	"Fetch",
	"Fey'ri",
	"Feytouched",
	"Fhorge",
	"Fiendish Creature",
	"Fiendwurm",
	"Fihyr",
	"Greater Fihyr",
	"Firbolg",
	"Giant Firefly",
	"Firenewt",
	"Fireshadow",
	"Celestial  Firre",
	"Greater Flame Snake",
	"Lesser Flame Snake",
	"Minor Flame Snake",
	"Flameskull",
	"Flesh Jelly",
	"Folugub",
	"Fomorian",
	"Forest Sloth",
	"Forgewraith",
	"Forlorn Husk",
	"Formarian",
	"Armadon Formarian",
	"Observer Formarian",
	"Winged Warrior Formarian",
	"Formian",
	"Formian Myrmarch",
	"Formian Queen",
	"Formian Taskmaster",
	"Formian Warrior",
	"Formian Worker",
	"Forsaken Shell",
	"Fossergrim",
	"Foulwing",
	"Arctic Fox",
	"Giant Frog",
	"Frost Folk",
	"Frost Giant Jarl",
	"Jotunheim Frost Giant",
	"Frost Salamander",
	"Frost Worm",
	"Fungus",
	"Galeb Duhr",
	"Gambol",
	"Garbler",
	"Gargoyle",
	"Kir-Lanan Gargoyle",
	"Feral  Gargun",
	"Gas Spore",
	"Gaspar",
	"Gathra",
	"Gauntlet Guardian",
	"Gelatinous Cube",
	"Genie",
	"Dao Genie",
	"Khayal Genie",
	"Marid Genie",
	"Qorrashi Genie",
	"Genius Loci",
	"Geriviar",
	"Ghaele",
	"Ghargatula",
	"Ghast",
	"Ghaunadan",
	"Shadow Beast Ghirrash",
	"Ghost",
	"Ghost",
	"Ghost",
	"Ghost Brute",
	"Frostfell Ghost",
	"Ghosteater",
	"Ghoul",
	"Abyssal Ghoul",
	"Abyssal Ghoul",
	"Giant",
	"Giant",
	"Giant",
	"Bog Giant",
	"Cloud Giant",
	"Death Giant",
	"Draconic Fire Giant",
	"Eldritch Giant",
	"Eldritch Confessor Giant",
	"Fire Giant",
	"Fog Giant",
	"Forest Giant",
	"Frost Giant",
	"Frost Giant",
	"Frost Mauler Giant",
	"Frost Spiritspeaker Giant",
	"Frost Tundra Scout Giant",
	"Greater Dusk Giant",
	"Least Dusk Giant",
	"Lesser Dusk Giant",
	"Mountain Giant",
	"Muspelheim Fire Giant",
	"Ocean Giant",
	"Phaerlin Giant",
	"Sand Giant",
	"Sand Champion Giant",
	"Shadow Giant",
	"Stone Giant",
	"Stone Elder Giant",
	"Storm Giant",
	"Sun Giant",
	"Totem Giant",
	"Gibbering Mouther",
	"Gibbering Mouther",
	"Gibbering Orb",
	"Gibberling",
	"Girallon",
	"Githyanki",
	"Githyanki",
	"Psionic Githyanki",
	"Githzerai",
	"Githzerai",
	"Psionic Githzerai",
	"Glabrezu",
	"Glaistig",
	"Glaistig Mindbender",
	"Glimmerskin",
	"Glitterfire",
	"Gloom",
	"Gloura",
	"Glyptodon",
	"Gnoll",
	"Flind Gnoll",
	"Gnome",
	"Chaos  Gnome",
	"Fire Gnome",
	"Forest Gnome",
	"Svirfneblim Gnome",
	"Whisper  Gnome",
	"Goatfolk",
	"Goblin",
	"Dekanter Goblin",
	"Forestkith Goblin",
	"Snow Goblin",
	"Golden Protector",
	"Golem",
	"Golem",
	"Golem",
	"Golem",
	"Golem",
	"Golem",
	"Adamantine Golem",
	"Alchemical Golem",
	"Blood of Hextor Golem",
	"Brain Golem",
	"Brass Golem",
	"Cadaver Golem",
	"Chain Golem",
	"Clay Golem",
	"Coral Golem",
	"Demonflesh Golem",
	"Diamond Gemstone Golem",
	"Dragonbone Golem",
	"Dragonflesh Golem",
	"Drakestone Golem",
	"Emerald Gemstone Golem",
	"Equine Golem",
	"Flesh Golem",
	"Gloom Golem",
	"Grave Dirt Golem",
	"Hangman Golem",
	"Hellfire Golem",
	"Ice Golem",
	"Incarnum Golem",
	"Iron Golem",
	"Ironwyrm Golem",
	"Mithral Golem",
	"Mud Golem",
	"Prismatic Golem",
	"Ruby Gemstone Golem",
	"Sand Golem",
	"Serpentflesh Golem",
	"Shadesteel Golem",
	"Shadesteel Greater Golem",
	"Spiderstone Golem",
	"Stained Glass Golem",
	"Stone Golem",
	"Stone Greater Golem",
	"Thayan Golem",
	"Web Golem",
	"Gorgon",
	"Demon  Goristro",
	"Gorynych",
	"Gravecrawler",
	"Gravehound",
	"Gravetouched Ghoul",
	"Gravewright",
	"Gravorg",
	"Gray Glutton",
	"Gray Jester",
	"Gray Render",
	"Green Warder",
	"Greenbound Creature",
	"Greenvise",
	"Grell",
	"Grell",
	"Grick",
	"Griffon",
	"Grig",
	"Grimalkin",
	"Grimlock",
	"Grimweird",
	"Grisgol",
	"Grizzly Mastodon",
	"Groundling",
	"Guardgoyle",
	"Guardinal",
	"Guardinal",
	"Avoral Guardinal",
	"Equinal Guardinal",
	"Musteval Guardinal",
	"Ursinal Guardinal",
	"Gulgar",
	"Gulguthydra",
	"Gynosphinx",
	"Hadozee",
	"Hadozee First Mate",
	"Hag",
	"Annis Hag",
	"Dune Hag",
	"Dusk Hag",
	"Green Hag",
	"Night Hag",
	"Sea Hag",
	"Shrieking Hag",
	"Hagspawn",
	"Half-Celestial",
	"Half-Dragon",
	"Half-Dragon",
	"Faerunian  Half-Dragon",
	"Half-Elemental",
	"Half-Elemental",
	"Half-Elf",
	"Half-Farspawn",
	"Half-Fey Centaur",
	"Half-Fey Template",
	"Half-Fiend",
	"Half-Fiend",
	"Half-Giant",
	"Half-Golem",
	"Clay Half-Golem",
	"Flesh Half-Golem",
	"Iron Half-Golem",
	"Stone Half-Golem",
	"Half-Illithid",
	"Half-Illithid Lizardfolk",
	"Half-Illithid Template",
	"Half-Janni",
	"Halfling",
	"Deep Halfling",
	"Tallfellow Halfling",
	"Half-Ogre",
	"Half-Orc",
	"Half-Troll Barbazu",
	"Half-Troll Template",
	"Half-Vampire",
	"Hammerclaw",
	"Hannya",
	"Harakin",
	"Elemental Grue Harginn",
	"Harpy",
	"Harpy Archer",
	"Harrier",
	"Harssaf",
	"Hawk",
	"Dire Hawk",
	"Dire Hawk",
	"Dire Hawk",
	"Hebi-No-Onna",
	"Hell Hound",
	"Nessian Warhound Hell Hound",
	"Hellcat",
	"Hellfire Wyrm",
	"Helmed Horror",
	"Helmed Horror",
	"Hengeyokai",
	"Hezrou",
	"Hieracosphinx",
	"Hill giant",
	"Hippocampus",
	"Hippocampus",
	"Hippogriff",
	"Pseudonatural Hippogriff",
	"Hippopotamus",
	"Dire Hippopotamus",
	"Hoard Scarab",
	"Hoary Hunter",
	"Hoary Steed",
	"Hobgoblin",
	"Hobyah",
	"Hollyphant",
	"Homunculus",
	"Dedicated Wright Homunculus",
	"Expeditious Messenger Homunculus",
	"Furtive Flicher Homunculus",
	"Iron Defender Homunculus",
	"Packmate Homunculus",
	"Hooded Pupil",
	"Hook Horror",
	"Hopping Vampire",
	"Horned Beast",
	"Horned Devil",
	"Horrid Animal",
	"Adamantine Horror",
	"Electrum Horror",
	"Gold Horror",
	"Platinum Horror",
	"Horse",
	"Dire Horse",
	"Dire Horse",
	"Heavy Horse",
	"Legendary Horse",
	"Light Horse",
	"Valenar Riding Horse",
	"Hound of the Gloom",
	"Mastiff Hound",
	"Howler",
	"Huecuva",
	"Huecuva",
	"Hulking Corpse",
	"Hullathoin",
	"Human Einherjar",
	"Hunefer",
	"Hybsil",
	"Hydra",
	"Hyena",
	"Ibis",
	"Ibrandlin",
	"Ice Beast",
	"Ice Devil",
	"Elder Ice Paraelemental",
	"Greater Ice Paraelemental",
	"Huge Ice Paraelemental",
	"Large Ice Paraelemental",
	"Medium Ice Paraelemental",
	"Small Ice Paraelemental",
	"Ice Serpent",
	"Icegaunt",
	"Elemental Grue Ildriss",
	"Illithidae",
	"Embrac Illithidae",
	"Kigrid Illithidae",
	"Saltor Illithidae",
	"Illumian",
	"Immoth",
	"Imp",
	"Imp",
	"Bloodbag Imp",
	"Euphoric Imp",
	"Filth Imp",
	"Indricothere",
	"Ineffable Horror",
	"Inevitable",
	"Inevitable",
	"Kolyarut Inevitable",
	"Kolyarut Inevitable",
	"Marut Inevitable",
	"Marut Inevitable",
	"Quarut Inevitable",
	"Varakhut Inevitable",
	"Zelekhut Inevitable",
	"Zelekhut Inevitable",
	"Inspired",
	"Intellect Devourer",
	"Invisible Stalker",
	"Iron Cobra",
	"Ironclad Mauler",
	"Ironmaw",
	"Ironthorn",
	"Ithyak-Ortheel",
	"Ixitxachitl",
	"Average Ixitxachitl",
	"Vampiric Ixitxachitl",
	"Ixzan",
	"Jackal",
	"Jackal Lord",
	"Dire Jackal",
	"Jackelwere",
	"Jaculi",
	"Jahi",
	"Janni",
	"Jarilith",
	"Jermlaine",
	"Jiki-Ketsu-Gaki",
	"Jiki-Niku-Gaki",
	"Jovoc",
	"Juggernaut",
	"Julajimas",
	"Jumping Caltrop",
	"Justicator",
	"Kaorti",
	"Kappa",
	"Karsite",
	"Keening Spirit",
	"Keeper",
	"Kelp Angler",
	"Kelpie",
	"Kelubar",
	"Kelvezu",
	"Kenku",
	"Kenku Sneak",
	"Kezef the Chaos Hound",
	"Khaasta",
	"Shadow Beast Khumat",
	"Ki-Rin",
	"Klurichir",
	"Kobold",
	"Kocrachon",
	"Kopru",
	"Korobokuru",
	"Kraken",
	"Krenshar",
	"Adult Kruthik",
	"Greater Kruthik",
	"Hatchling Kruthik",
	"Kuldurath",
	"Kuo-toa",
	"Kuo-Toa Leviathan",
	"Kython",
	"Adult Kython",
	"Broodling Kython",
	"Impaler Kython",
	"Juvenile Kython",
	"Slaughterking Kython",
	"Slaymaster Kython",
	"Lamia",
	"Lammasu",
	"Landwyrm",
	"Desert Landwyrm",
	"Forest Landwyrm",
	"Hill Landwyrm",
	"Jungle Landwyrm",
	"Mountain Landwyrm",
	"Plains Landwyrm",
	"Swamp Landwyrm",
	"Tundra Landwyrm",
	"Underdark Landwyrm",
	"Laraken",
	"Lavawight",
	"Giant Leech",
	"Leechwalker",
	"Legendary Animal",
	"Legendary Animal",
	"Legendary Ape",
	"Legendary Bear",
	"Legendary Eagle",
	"Legendary Horse",
	"Legendary Shark",
	"Legendary Snake",
	"Legendary Tiger",
	"Legendary Wolf",
	"Lemure",
	"Leonal",
	"Celestial  Leonal",
	"Leopard",
	"LeShay",
	"Leskylor",
	"Three-Headed Leskylor",
	"Leucrotta",
	"Leucrotta",
	"Changesteed Leucrotta",
	"Leviathan",
	"Lhosk",
	"Li Lung",
	"Lich",
	"Dry  Lich",
	"Lillend",
	"Limbo Stalker",
	"Linnorm",
	"Corpse-Tearer Linnorn",
	"Dread Linnorn",
	"Gray Linnorn",
	"Lion",
	"Dire Lion",
	"Sea Lion",
	"Lith",
	"Living Blasphemy",
	"Living Holocaust",
	"Living Spell",
	"Living Spell",
	"Living Vault",
	"Living Zombie",
	"Lizard",
	"Lizard King/Queen",
	"Giant Banded Lizard",
	"Horned Lizard",
	"Monitor Lizard",
	"Pack Lizard",
	"Riding Lizard",
	"Spitting Crawler Lizard",
	"Subterranean Lizard",
	"Woodling Monitor Lizard",
	"Lizardfolk",
	"Blackscale Lizardfolk",
	"Poison Dusk Lizardfolk",
	"Poison Dusk Lieutenant Lizardfolk",
	"Locathah",
	"Loquasphinx",
	"Lost",
	"Loxo",
	"Loxo",
	"Loxo",
	"Lucent Worm",
	"Lumi",
	"Lumi Crusader",
	"Luna Moth",
	"Lung Wang",
	"Lupinal",
	"Lurker",
	"Lurking Strangler",
	"Drow Werebat Lycanthrope",
	"Werecat Lycanthrope",
	"Werecrododile Lycanthrope",
	"Wereserpent Lycanthrope",
	"Wereshark Lycanthrope",
	"Lynx",
	"Mad Slasher",
	"Maelephant",
	"Maenad",
	"Magebred Animal",
	"Dire Maggot",
	"Giant Maggot",
	"Magister",
	"Magma Hurler",
	"Elder Magma Paraelemental",
	"Greater Magma Paraelemental",
	"Huge Magma Paraelemental",
	"Large Magma Paraelemental",
	"Medium Magma Paraelemental",
	"Small Magma Paraelemental",
	"Magmin",
	"Malasynep",
	"Malasynep Mindmage",
	"Malaugrym",
	"Malebranche",
	"the Branded King Malikizid",
	"Mamono",
	"Mane",
	"Manta Ray",
	"Manticore",
	"Mantimera",
	"Marilith",
	"Marrash",
	"Marrulurk",
	"Marrusault",
	"Marruspawn",
	"Marruspawn Abomination",
	"Marrutact",
	"Marzanna",
	"Mastadon",
	"Maug",
	"Maulgoth",
	"Maur",
	"Maurezhi",
	"Meazel",
	"Medusa",
	"Meenlock",
	"Megaloceros",
	"Megalodon",
	"Megapede",
	"Megatherium",
	"Mephit",
	"Air Mephit",
	"Dust Mephit",
	"Earth Mephit",
	"Fire Mephit",
	"Glass Mephit",
	"Ice Mephit",
	"Magma Mephit",
	"Ooze Mephit",
	"Salt Mephit",
	"Steam Mephit",
	"Sulfur Mephit",
	"Water Mephit",
	"Mercane",
	"Mercane",
	"Merfolk",
	"Metalmaster",
	"Yugoloth Mezzoloth",
	"Midnight Construct",
	"Mimic",
	"Mind Flayer",
	"Mind Flayer Sorcerer",
	"Alhoon Mind Flayer",
	"Paragon Mind Flayer",
	"Psionic Mind Flayer",
	"Ulitharid Mind Flayer",
	"Ulitharid Psionic Mind Flayer",
	"Vampire Mind Flayer",
	"Mindshredder",
	"Mindshredder Larva",
	"Mindshredder Warrior",
	"Mindshredder Zenthral",
	"Mineral Warrior",
	"Minion of Set",
	"Minotaur",
	"Minotaur of Krynn",
	"Minotaur of Legend",
	"Mirage Mullah",
	"Mivilorn",
	"Mlarraun",
	"Mohrg",
	"Mongrelfolk",
	"Mongrelfolk",
	"Monkey",
	"Air Monolith",
	"Earth Monolith",
	"Fire Monolith",
	"Water Monolith",
	"Monster of Legend",
	"Moon Dog",
	"Moonbeast",
	"Mooncalf",
	"Mooncalf",
	"Moonrat",
	"Morkoth",
	"Movanic",
	"Mu Spore",
	"Muckdweller",
	"Mudmaw",
	"Mule",
	"Mumia",
	"Mummified Creature",
	"Mummy",
	"Mummy Lord",
	"Greater  Mummy",
	"Salt Mummy",
	"Murk",
	"Mur-Zhagul",
	"Myconid",
	"Average Worker Myconid",
	"Circle Leader Myconid",
	"Elder Worker Myconid",
	"Guard Myconid",
	"Junior Worker Myconid",
	"Sovereign Myconid",
	"Myrlochar",
	"Myrmyxicus",
	"Naga",
	"Asp Naga",
	"Banelar Naga",
	"Bone Naga",
	"Bone  Naga",
	"Chameleon Naga",
	"Cobra Naga",
	"Constrictor Naga",
	"Dark Naga",
	"Greensnake Naga",
	"Guardian Naga",
	"Ha-Naga Naga",
	"Iridescent Naga",
	"Spirit Naga",
	"Water Naga",
	"Nagahydra",
	"Nalfeshnee",
	"Devil  Narzugon",
	"Einsaung Nat",
	"Hkum Yeng Nat",
	"Lu Nat",
	"Large Nature Spirit",
	"Medium Nature Spirit",
	"Small Nature Spirit",
	"Neanderthal",
	"Necromental",
	"Necronaut",
	"Necrophidius",
	"Necroplasm",
	"Necropolitan",
	"Necrothane",
	"Needlefolk",
	"Neh-Thalggu",
	"Neogi",
	"Adult Neogi",
	"Great Old Master Neogi",
	"Spawn Neogi",
	"Neothelid",
	"Nereid",
	"Nerra",
	"Kalareem Nerra",
	"Sillit Nerra",
	"Varoot Nerra",
	"Nethersight Mastiff",
	"Nezumi",
	"Nifern",
	"Night Hunter",
	"Night Twist",
	"Nightcrawler",
	"Nightmare",
	"Nightmare Beast",
	"Cauchemar Nightmare",
	"Cauchemar Nightmare",
	"Lesser Nightmare",
	"Nightshade",
	"Nighthaunt Nightshade",
	"Nightwalker",
	"Nightwing",
	"Nilshai",
	"Nimblewright",
	"Nishruu",
	"Nishruu",
	"Nixie",
	"Nothic",
	"Yugoloth Nycaloth",
	"Nycter",
	"Nycter Defender of the Cave",
	"Nymph",
	"Nyth",
	"Ocean Strider",
	"Ochre Jelly",
	"Octopus",
	"Octopus Tree",
	"Giant Octopus",
	"Ocularon",
	"Odopi",
	"Elder Odopi",
	"Ogre",
	"Ogre Barbarian",
	"Ogre Mage",
	"Skullcrusher Ogre",
	"Skullcrusher Sergeant Ogre",
	"Omnimental",
	"Akuma no Oni",
	"Ashi no Oni",
	"Byoki no Oni",
	"Common Oni",
	"Gekido no Oni",
	"Go-Zu Oni",
	"Haino no Oni",
	"Kamu no Oni",
	"Kyoso no Oni",
	"Me-Zu Oni",
	"Sanru no Oni",
	"Shikibu no Oni",
	"Tsuburu no Oni",
	"Ugulu no Oni",
	"Yattoko no Oni",
	"Onikage",
	"Ooze",
	"Elder Ooze Paraelemental",
	"Greater Ooze Paraelemental",
	"Huge Ooze Paraelemental",
	"Large Ooze Paraelemental",
	"Medium Ooze Paraelemental",
	"Small Ooze Paraelemental",
	"Aquatic Ooze",
	"Arcane Ooze",
	"Bone Ooze",
	"Brine Ooze",
	"Conflagration Ooze",
	"Dissolution Ooze",
	"Ethereal Ooze",
	"Flotsam Ooze",
	"Gray Ooze",
	"Infernal Conflagration Ooze",
	"Lava Ooze",
	"Snowflake Ooze",
	"Summoning Ooze",
	"Void Ooze",
	"Ophidian",
	"Orb Wraith",
	"Orc",
	"Snow Shaman Orc",
	"Orca",
	"Orcwort",
	"Oread",
	"Orglash",
	"Ormyrr",
	"Osquip",
	"Otter",
	"Sea Otter",
	"Otyugh",
	"Lifeleech Otyugh",
	"Owl",
	"Giant Owl",
	"Giant Owl",
	"Owlbear",
	"Pack Fiend",
	"Paeliryon",
	"Painspeaker",
	"Palrethee",
	"Pan Lung",
	"Pegasus",
	"Penguin",
	"Pennaggolan",
	"Homunculus Persistent Harrier",
	"Peryton",
	"Petal",
	"Petitioner",
	"Phaerimm",
	"Phaerimm",
	"Phaerlock",
	"Phantasmal Slayer",
	"Phantom Fungus",
	"Phargion",
	"Phase Wasp",
	"Phasm",
	"Phiuhl",
	"Phoelarch",
	"Phoenix",
	"Phoera",
	"Phrenic Creature",
	"Phthisic",
	"Pit Fiend",
	"Pixie",
	"Plague Blight",
	"Plague Brush",
	"Plague Spewer",
	"Planetar",
	"Planetouched",
	"Planetouched",
	"Planetouched",
	"Aasimar Planetouched",
	"Air Genasi Planetouched",
	"Chaon Planetouched",
	"Earth Genasi Planetouched",
	"Fire Genasi Planetouched",
	"Maeluth Planetouched",
	"Mechanatrix Planetouched",
	"Shyft Planetouched",
	"Tiefling Planetouched",
	"Water Genasi Planetouched",
	"Wispling Planetouched",
	"Zenythri Planetouched",
	"Dire Polar Bear",
	"Pony",
	"War Pony",
	"Porcupine Cactus",
	"Porpoise",
	"Portal Drake",
	"Giant Praying Mantis",
	"Prismasaurus",
	"Protean Scourge",
	"Protean Scourge Arcanist",
	"Hagunemnon Protean",
	"Protectar",
	"Pseudodragon",
	"Pseudonatural Creature",
	"Pseudonatural Creature",
	"Psicrystal",
	"Psion-Killer",
	"Psurlon",
	"Psurlon",
	"Average Psurlon",
	"Average Psurlon",
	"Elder Psurlon",
	"Elder Psurlon",
	"Giant Psurlon",
	"Giant Psurlon",
	"Pterafolk",
	"Pteranadon",
	"White Pudding",
	"Dire Puma",
	"Puppeteer",
	"Flesh Harrower Puppeteer",
	"Purple Worm",
	"Pyrohydra",
	"Quaggoth",
	"Quaraphon",
	"Quaraphon Bully",
	"Quasit",
	"Quell",
	"Quesar",
	"Quth-Maren",
	"Quth-Maren",
	"Radiant Idol",
	"Rage Drake",
	"Fiendish Rage Drake",
	"Ragewalker",
	"Ragewind",
	"Raggamoffyn",
	"Common Raggamoffyn",
	"Guttersnipe Raggamoffyn",
	"Shrapnyl Raggamoffyn",
	"Tatterdemanimal Raggamoffyn",
	"Raiment",
	"Rainbow Crow",
	"Rakka",
	"Rakshasa",
	"Ak'chazar Rakshasa",
	"Naztharune Rakshasa",
	"Zakya Rakshasa",
	"Ramadeen",
	"Ramfish",
	"Rampager",
	"Raptoran",
	"Rast",
	"Rat",
	"Dire Rat",
	"Raven",
	"Giant Raven",
	"Giant Raven",
	"Ravid",
	"Reason Stealer",
	"Red Sundew",
	"Redcap",
	"Elder Redcap",
	"Young Redcap",
	"Reekmurk",
	"Rejkar",
	"Remorhaz",
	"Retriever",
	"Revenant",
	"Revenant",
	"Revived Fossil",
	"Rhek",
	"Chaosgrinder Rhek",
	"Rhinoceros",
	"Dire Rhinoceros",
	"Warbeast Rhinoceros",
	"Rilkan",
	"Rilmani",
	"Aurumach Rilmani",
	"Cuprilach Rilmani",
	"Ferrumach Rilmani",
	"Rimefire Eidolon",
	"Roach Thrall",
	"Roc",
	"Rock Wyrm",
	"Rogue Eidolon",
	"Rokuro-Kubi",
	"Roper",
	"Primastic Roper",
	"Rot Reaver",
	"Deep Rothe",
	"Ghost Rothe",
	"Surface Rothe",
	"Roving Mauler",
	"Rukanyr",
	"Rukarazyll",
	"Runehound",
	"Runic Guardian",
	"Rusalka",
	"Rust Monster",
	"Rutterkin",
	"Sacred Watcher",
	"Saguaro Sentinel",
	"Sahuagin",
	"Saint",
	"Salamander",
	"Average Salamander",
	"Flamebrother Salamander",
	"Noble Salamander",
	"Sanctified Creature",
	"Sand Hunter",
	"Sarkrith",
	"Spelleater Sarkrith",
	"Thane Sarkrith",
	"Sarrukh",
	"Satyr",
	"Scaladar",
	"Scalamagdrion",
	"Scaled Stalker",
	"Giant Whip Scorpion",
	"Monstrous Scorpion",
	"Scorpionfolk",
	"Scyllan",
	"Sea Kin",
	"Seal",
	"Seal",
	"Seawolf",
	"Selkie",
	"Senmurv",
	"Serval",
	"Seryulin",
	"Greater Seryulin",
	"Sewerm",
	"Shaboath",
	"Shadar-Kai",
	"Shade",
	"Shadow",
	"Shadow Asp",
	"Shadow Creature",
	"Shadow Creature",
	"Shadow Demon",
	"Shadow Jelly",
	"Shadow Mastiff",
	"Shadow of the Void",
	"Shadow Sibling",
	"Greater Shadow",
	"Shadowperson",
	"Shadowwalker",
	"Shadurakul",
	"Shalarin",
	"Shambling Mound",
	"Shape of Fire",
	"Sharakim",
	"Shark",
	"Dire Shark",
	"Huge Shark",
	"Large Shark",
	"Legendary Shark",
	"Medium Shark",
	"Sharn",
	"Shator",
	"Shedu",
	"Shen Lung",
	"Shield Guardian",
	"Shifter",
	"Shikki-Gaki",
	"Shinen-Gaki",
	"Shirokinu-Katsukami",
	"Shivhad",
	"Shocker",
	"Shocker Lizard",
	"Shredstorm",
	"Shrieker",
	"Shrieking Terror",
	"Sickening Sleep",
	"Greater Siege Crab",
	"Siege Crag",
	"Silthilar",
	"Silveraith",
	"Sinister",
	"Sirine",
	"Sirrush",
	"Sisiutl",
	"Siv",
	"Skarn",
	"Skeletal Warbeast",
	"Skeletal Warrior",
	"Skeleton",
	"Advanced Megaraptor Skeleton",
	"Chimera Skeleton",
	"Cloud Giant Skeleton",
	"Ettin Skeleton",
	"Human Warrior Skeleton",
	"Karrnathi Skeleton",
	"Owlbear Skeleton",
	"Troll Skeleton",
	"Wolf Skeleton",
	"Young Adult Red Dragon Skeleton",
	"Skin Kite",
	"Skindancer",
	"Skirr",
	"Skulk",
	"Skulk",
	"Skulking Cyst",
	"Skulvyn",
	"Skum",
	"Skybleeder",
	"Slaad",
	"Black Slaad",
	"Blue Slaad",
	"Death Slaad",
	"Gray Slaad",
	"Green Slaad",
	"Mud Slaad",
	"Red Slaad",
	"White Slaad",
	"Slasrath",
	"Slaughter Wight",
	"Slaughterhouse Behemoth",
	"Slaughterhouse Eviscerator",
	"Slaymate",
	"Smilodon",
	"Elder Smoke Paraelemental",
	"Greater Smoke Paraelemental",
	"Huge Smoke Paraelemental",
	"Large Smoke Paraelemental",
	"Medium Smoke Paraelemental",
	"Small Smoke Paraelemental",
	"Snake",
	"Dire Snake",
	"Dire Snake",
	"Dung Snake",
	"Flying Snake",
	"Glacier Snake",
	"Legendary Snake",
	"Reed Snake",
	"Sea Snake",
	"Two-headed Adder Snake",
	"Viper Snake",
	"Winged Viper Snake",
	"Snapping Turtle",
	"Snowcloak",
	"Snowcloak",
	"Solar",
	"Souleater",
	"Soulfused Construct",
	"Spiritovore Energon Soulmarauder",
	"Spiritovore Energon Soulscaper",
	"Spiritovore Energon Soulsipper",
	"Soulspark",
	"Spark Guardian",
	"Spark Lasher",
	"Spawn of Kyuss",
	"Spectral Lurker",
	"Spectral Lyrist",
	"Spectral Mage",
	"Spectral Minion",
	"Spectral Panther",
	"Spectral Steed",
	"Spectre",
	"Fire Spectre",
	"Spell Weaver",
	"Spellgaunt",
	"Spellscale",
	"Spellstiched Ghast",
	"Spellstitched",
	"Spellstitched Creature",
	"Spellwarped Creature",
	"Spellwarped Ettin",
	"Spellwurm",
	"Sphinx",
	"Canisphinx Sphinx",
	"Crocosphinx Sphinx",
	"Saurosphinx Sphinx",
	"Threskisphinx Sphinx",
	"Spider Eater",
	"Devastation Spider",
	"Giant Sun Spider",
	"Giant Whip Spider",
	"Hairy Spider",
	"Hairy Spider",
	"Harpoon Spider",
	"Harpoon Dread Spider",
	"Jade Spider",
	"Monstrous Spider",
	"Monstrous Diving Spider",
	"Phase Spider",
	"Shadow Spider",
	"Snow Spider",
	"Sword Spider",
	"Devil  Spinagon",
	"Spirit Animal",
	"Spirit Folk",
	"Spirit Folk",
	"Spirit of the Air",
	"Spirit of the Land",
	"Spirit Tree",
	"Splinterwaif",
	"Splinterwaif Knave",
	"Sporebat",
	"Spriggan",
	"Sprite",
	"Squamous Spewer",
	"Squid",
	"Giant Squid",
	"Ssvaklor",
	"Greater Ssvaklor",
	"Starsnake",
	"Starwhale",
	"Steeder",
	"Steel Predator",
	"Steel Predator",
	"Stegosaurus",
	"Stinger",
	"Stingray",
	"Stingtail",
	"Stirge",
	"Stone Flyer",
	"Stone Spike",
	"Stonechild",
	"Stonesinger",
	"Stormstalk",
	"Giant Strider",
	"Succubus",
	"Sunwyrm",
	"Susurrus",
	"Swamplight Lynx",
	"Swarm",
	"Swarm",
	"Swarm",
	"Abyssal Ant Swarm",
	"Air Elementite Swarm",
	"Apocalypse Frog Swarm",
	"Bat Swarm",
	"Bloodfiend Locust Swarm",
	"Bone Rat Swarm",
	"Bronze Locust Swarm",
	"Brood Keeper Larva Swarm",
	"Centipede Swarm",
	"Cinder Swarm",
	"Corpse Rat Swarm",
	"Cranium Rat Average Pack Swarm",
	"Cranium Rat Greater Pack Swarm",
	"Cranium Rat Lesser Pack Swarm",
	"Deathraven Swarm",
	"Divine Wrath Swarm",
	"Dread Blossom Swarm",
	"Earth Elementite Swarm",
	"Ephemeral Swarm",
	"Fire Elementite Swarm",
	"Hellwasp Swarm",
	"Hoard Scarab Swarm",
	"Jellyfish Swarm",
	"Leech Swarm",
	"Locust Swarm",
	"Murder of Crows Swarm",
	"Needletooth Swarm",
	"Piranha Swarm",
	"Plague Ant Swarm",
	"Rancid Beetle Swarm",
	"Rapture Locust Swarm",
	"Rat Swarm",
	"Ruin Swarm",
	"Scarab Beetle Swarm",
	"Scarab Death Swarm",
	"Scorpion Swarm",
	"Shimmerling Swarm",
	"Spider Swarm",
	"Sunfly Swarm",
	"Swamp Strider Swarm",
	"Viper Swarm",
	"Wasp Swarm",
	"Water Elementite Swarm",
	"Swarm-Shifter",
	"Swordwraith Template",
	"Sylph",
	"Living Breastplate Symbiont",
	"Tentacle Whip Symbiont",
	"Tongueworm Symbiont",
	"Taer",
	"Elder Taint Elemental",
	"Greater Taint Elemental",
	"Huge Taint Elemental",
	"Large Taint Elemental",
	"Medium Taint Elemental",
	"Small Taint Elemental",
	"Tainted Minion",
	"Tainted Raver",
	"Tako",
	"Tall Mouther",
	"Tall Mouther",
	"Tanarukk",
	"Tarmak",
	"Tarrasque",
	"Tasloi",
	"Tasloi",
	"Tauric Creature",
	"Tauric Hobgoblin-Griffon",
	"Tayellah",
	"Teant",
	"Telthor",
	"Temporal Filcher",
	"Tendriculos",
	"Crow-Headed Tengu",
	"Human-Headed Tengu",
	"Teratomorph",
	"Terlen",
	"Queen Termite",
	"Soldier Termite",
	"Worker Termite",
	"Terror Bird",
	"Five-Headed Terror",
	"Ten-Headed Terror",
	"Thanoi",
	"Shadow Beast Thaskor",
	"Thomil",
	"Thoqqua",
	"Thorciasid",
	"Thorn",
	"Thought Eater",
	"Thought Slayer",
	"Thri-Kreen",
	"Thri-Kreen",
	"Thri-Kreen",
	"Thri-Kreen",
	"Throwing Scarab",
	"Thrum Worm",
	"Thudhunter",
	"Thunder Worm",
	"Thunderbird",
	"the Chromatic Dragon Tiamat",
	"Tiefling",
	"T'ien Lung",
	"Tiger",
	"Dire Tiger",
	"Legendary Tiger",
	"Legendary Tiger",
	"Red Tiger",
	"Sea Tiger",
	"Ti-Khana Template",
	"Titan",
	"Elder Titan",
	"Titanic Creature",
	"Tlalusk",
	"Toad",
	"Dire Toad",
	"Dire Toad",
	"Fire Toad",
	"Giant Toad",
	"Ice Toad",
	"Ice Toad",
	"Poisonous Toad",
	"Titanic Toad",
	"Tojanida",
	"Adult Tojanida",
	"Elder Tojanida",
	"Juvenile Tojanida",
	"Tomb Mote",
	"Tomb Tapper",
	"Tomb Tapper",
	"Tooth Beast",
	"Topiary Guardian",
	"Alternative Topiary Guardian",
	"Boar Topiary Guardian",
	"Lion Topiary Guardian",
	"Triceratops Topiary Guardian",
	"Dire Tortoise",
	"Elder Treant",
	"Tree Python",
	"Tren",
	"Tressym",
	"Tressym",
	"Trilloch",
	"Triton",
	"Troglodyte",
	"Troll",
	"Troll Hunter",
	"Cave Troll",
	"Crystalline Troll",
	"Fell Troll",
	"Forest Troll",
	"Ice Troll",
	"Mountain Troll",
	"Psuedonatural Troll",
	"War Troll",
	"Wasteland Troll",
	"Tsucora Quori",
	"Tsuno",
	"Tumbling Mound",
	"Tun Mi Lung",
	"Tunnel Terror",
	"Tusked Behemoth",
	"Twig Blight",
	"Twig Blight",
	"Uchuulon",
	"Udoroot",
	"Uldra",
	"Ulgurstasta",
	"Yugoloth Ultroloth",
	"Umber Hulk",
	"Truly Horrid Umber Hulk",
	"Ephemera Umbral Banyan",
	"Umbral Blot",
	"Umbral Creature",
	"Unbodied",
	"Undead Martyr",
	"Underfolk",
	"Undying Councilor",
	"Undying Soldier",
	"Undying Wizard",
	"Unholy Scion",
	"Unicorn",
	"Black Unicorn",
	"Celestial Charger Unicorn",
	"Unraveler",
	"Urdark",
	"Ur'epona",
	"Demon  Uridezu",
	"Urophion",
	"Urskan",
	"Uthraki",
	"Uvuudaum",
	"Vaath",
	"Valkyrie",
	"Valkyries' Mount",
	"Vampire",
	"Vampire Spawn",
	"Monstrous  Vampire",
	"Vaporighu",
	"Elemental Grue Vardigg",
	"Vargouille",
	"Varrangoin",
	"Arcanist Varrangoin",
	"Lesser Varrangoin",
	"Rager Varrangoin",
	"Vasuthant",
	"Horrific Vasuthant",
	"Giant Velvet Worm",
	"Vermin Lord",
	"Vermiurge",
	"Vilewight",
	"Vine Horror",
	"Violet Fungus",
	"Celestial Viper",
	"Fiendish Viper",
	"Visage",
	"Visilight",
	"Vivacious Creature",
	"Vodyanoi",
	"Voidmind Creature",
	"Voidmind Grimlock",
	"Voidwraith",
	"Volodni",
	"Vorr",
	"Vour",
	"Vrock",
	"Vultivor",
	"Vulture",
	"Dire Vulture",
	"Walking Statue of Waterdeep",
	"Walking Wall",
	"Walrus",
	"Wang-Liang",
	"War Mastiff",
	"Warbeast",
	"Warbound Impaler",
	"Warforged",
	"Warforged Charger",
	"Warforged Scout",
	"Warforged Titan",
	"Heavy Warhorse",
	"Light Warhorse",
	"Giant Wasp",
	"Waste Crawler",
	"Wastrilith",
	"Watchspider",
	"Weasel",
	"Dire Weasel",
	"Air Weird",
	"Earth Weird",
	"Fire Weird",
	"Water Weird",
	"Wemic",
	"Wendigo Template",
	"Werebat",
	"Werebear",
	"Wereboar",
	"Werecrocodile",
	"Werecrocodile",
	"Wererat",
	"Wereshark",
	"Weretiger",
	"Werewolf",
	"Werewolf lord",
	"Whale",
	"Wheep",
	"Whipsnake",
	"Wicker Man",
	"Wight",
	"Dust Wight",
	"Will-o'-Wisp",
	"Wilora",
	"Windghost",
	"Winter Cyst",
	"Winter Wolf",
	"Winterspawn",
	"Winterwight",
	"Witchknife",
	"Witchknife Captain",
	"Wolf",
	"Dire Wolf",
	"Legendary Wolf",
	"Wolverine",
	"Dire Wolverine",
	"Wood Woad",
	"Woodling",
	"Woodling Druid",
	"Woolly Mammoth",
	"Worg",
	"Worm that Walks",
	"Wortling",
	"Wraith",
	"Colossal Wraith Spider",
	"Gargantuan Wraith Spider",
	"Huge Wraith Spider",
	"Large Wraith Spider",
	"Medium Wraith Spider",
	"Small Wraith Spider",
	"Incarnum Wraith",
	"Sea Wraith",
	"Wyste",
	"Wyste",
	"Wyvern",
	"Xag-Ya",
	"Xeph",
	"Xerfilstyx",
	"Xill",
	"Xorn",
	"Average Xorn",
	"Elder Xorn",
	"Minor Xorn",
	"Yak Folk",
	"Yellow Muck Zombie Template",
	"Yellow Musk Creeper",
	"Yellow Musk Zombie Orc",
	"Yeth Hound",
	"Yeti",
	"Yeti",
	"Abominable Yeti",
	"Yrthak",
	"Yu Lung",
	"Yuan-ti",
	"Yuan-ti",
	"Yuan-ti",
	"Yuan-ti Anathema",
	"Yuan-ti Halfblood",
	"Yuan-ti Holy Guardian",
	"Yuan-ti Mage Slayer",
	"Yuan-ti Pureblood",
	"Abomination Yuan-ti",
	"Halfblood Yuan-ti",
	"Psionic Yuan-ti",
	"Pureblood Yuan-ti",
	"Yuant-ti Abomination",
	"Yugoloth",
	"Yugoloth",
	"Arcanaloth Yugoloth",
	"Canoloth Yugoloth",
	"Echinoloth Yugoloth",
	"Marraenoloth Yugoloth",
	"Mezzoloth Yugoloth",
	"Nycaloth Yugoloth",
	"Nycaloth Commander Yugoloth",
	"Piscoloth Yugoloth",
	"Skeroloth Yugoloth",
	"Ultraloth Yugoloth",
	"Yyagnoloth Yugoloth",
	"Yuki-On-Na",
	"Yuki-On-Na",
	"Yurian",
	"Zaratan",
	"Zeugalak",
	"Zeuglodon",
	"Zezir",
	"Zodar",
	"Zombie",
	"Bugbear Zombie",
	"Gray Render Zombie",
	"Human Commoner Zombie",
	"Juju  Zombie",
	"Karrnathi Zombie",
	"Kobold Zombie",
	"Minotaur Zombie",
	"Necrocarnum Zombie",
	"Ogre Zombie",
	"Rancid Beetle Zombie",
	"Troglodyte Zombie",
	"Tyrantfog Zombie",
	"Umber Hulk Zombie",
	"Wyvern Zombie",
	"Zovvuut",
	"Astral Construct",
	"Agile Loper",
	"Alabaster Aerial",
	"Amber Tunneler",
	"Anathemic Carapace",
	"Astral Aquan",
	"Ebony Stinger",
	"Emerald Gyre",
	"Iridescent Serpent",
	"Ectoplasmic Swarm",
	"Arctine Elemental Steward",
	"Emberling Elemental Steward",
	"Geodite Elemental Steward",
	"Tempestan Elemental Steward",
	"Larval Flayer",
	"Shadow Fet",
	"Sibyllic Guardian",
	"Spectral Savant",
	"Armanite",
	"Bar-Lgura",
	"Broodswarm",
	"Bulezau",
	"Chasme",
	"Dybbuk",
	"Ekolid",
	"Goristro",
	"Guecubu",
	"Lilitu",
	"Mane",
	"Molydeus",
	"Nabassu",
	"Rutterkin",
	"Sibriex",
	"Yochlol",
	"Black Rock Triskelion",
	"Cyclonic Ravager",
	"Holocaust Disciple",
	"Waterveiled Assassin",
	"Balhannoth",
	"Bloodfire Ooze",
	"Bloodhulk Fighter",
	"Bloodhulk Giant",
	"Bloodhulk Crusher",
	"Bloodsilk Spider",
	"Briarvex",
	"Clockroach",
	"Clockwork Mender",
	"Clockwork Steed",
	"Concordant Killer",
	"Corrupture",
	"Defacer",
	"Deathdrinker",
	"Kastighur",
	"Nashrou",
	"Whisper Demon",
	"Demonhive Attendant",
	"Demonet Swarm",
	"Demonhive Queen",
	"Dwarf Ancestor",
	"Lolth's Sting",
	"Dark Sniper",
	"Arcane Guard",
	"Drow Priestess",
	"Craa'ghoran Giant",
	"Gish",
	"Githyanki Soldier",
	"Githyanki Captain",
	"Slave-Taker",
	"Fiendish Cleric of Yeenoghu",
	"Half-Fiend Gnoll Warlock",
	"Fang Golem",
	"Howler Wasp",
	"Howler Wasp Queen",
	"Inferno Spider",
	"Joystealer",
	"Justice Archon",
	"Justice Archon Champion",
	"Dark Talon Soldier",
	"Dark Talon Champion",
	"Dark Talon Wasp Rider",
	"Giant Wasp Mount",
	"Dark Talon Shaman",
	"Yarshag",
	"Giant Stag Beetle Vermin Companion",
	"Lodestone Marauder",
	"Lolth-Touched Bebilith",
	"Lolth-Touched Drow Ranger",
	"Lolth-Touched Monstrous Hunting Spider",
	"Lunar Ravager",
	"Mageripper Swarm",
	"Greathorn Minotaur",
	"Nagatha",
	"Necrosis Carnex",
	"Oaken Defender",
	"Ogre Scout",
	"Ogre Tempest",
	"Ogre Guard Thrall",
	"Orc Berserker",
	"War Howler",
	"Orc Battle Priest",
	"Orc Plague Speaker",
	"Half-Orc Infiltrator",
	"Plague Walker",
	"Quanlos",
	"Sailsnake",
	"Skiurid",
	"Blackspawn Raider",
	"Blackspawn Exterminator",
	"Blackspawn Stalker",
	"Bluespawn Ambusher",
	"Bluespawn Burrower",
	"Bluespawn Godslayer",
	"Bluespawn Stormlizard",
	"Greenspawn Leaper",
	"Greenspawn Razorfiend",
	"Greenspawn Sneak",
	"Greenspawn Sneak Raid Leader",
	"Redspawn Arcaniss",
	"Redspawn Firebelcher",
	"Whitespawn Hordeling",
	"Whitespawn Hunter",
	"Whitespawn Berserker",
	"Whitespawn Iceskidder",
	"Tomb Spider",
	"Tomb Spider Broodswarm",
	"Web Mummy",
	"Varag",
	"Varag Pack Leader",
	"Verdant Prince",
	"Vitreous Drinker",
	"Windrazor",
	"Windscythe",
	"Wizened Elder",
	"Wrackspawn",
	"Pureblood Slayer",
	"Halfblood Deceiver",
	"Abomination Cult Leader",
	"Yuan-ti Ignan",
	"Corruptor of Fate",
	"Corruptor of Fate Assassin",
	"Voor",
	"Dreadful Lasher",
	"Zern",
	"Zern Arcanovore",
	"Zern Blade Thrall",
	"Alchemy Beetle",
	"Dream Serpent",
	"Jungle Giant",
	"Primordial Giant",
	"Scorrow",
	"Tentacle Spider",
	"Quorcraft Warforged",
	"Warforged Scorpion",
	"Yuan-ti Wretchling",
	"Bluespawn Stoneglider",
	"Krathbairn",
	"Redspawn Birther",
	"Spectral Creature",
	"Mercury Dragon",
	"Steel Dragon",
	"Mist Dragon",
	"Naityan Rakshasa",
	"Reth Dekala",
	"Valkyrie",
	"Aspect of Bahamut",
	"Aspect of Tiamat",
	"Blazewyrm",
	"Drakkensteed",
	"Huitzil",
	"Phynxkin",
	"Dire Phynxkin",
	"Redspawn Berserker",
	"Spelleater",
	"Twilight Guardian",
	"Velroc",
	"Siege Golem",
	"Cesspit Ooze",
	"Ripper",
	"Sepulchral Thief",
	"Pest Swarm",
	"Zeitgeist",
	"Abishai",
	"Black  Abishai",
	"Blue  Abishai",
	"Green  Abishai",
	"Red  Abishai",
	"White  Abishai",
	"Amnizu",
	"Assassin Devil",
	"Ayperobos Swarm",
	"Harvester Devil",
	"Hellfire Engine",
	"Kalabon",
	"Legion Devil",
	"Malebranche",
	"Narzugon",
	"Nupperibo",
	"Orthon",
	"Paeliryon",
	"Pain Devil",
	"Pleasure Devil",
	"Spined Devil",
	"Steel Devil",
	"Xerfilstyx",
	"Aspect of Bel",
	"Aspect of Dispater",
	"Aspect of Mammon",
	"Aspect of Belial",
	"Aspect of Levistus",
	"Aspect of Glasya",
	"Aspect of Baalzebul",
	"Aspect of Mephistopheles",
	"Aspect of Asmodeus",
	"Ascomoid",
	"Rot Grub Swarm",
	"Acidborn Monster",
	"Dungeonbred Monster",
	"Guardian Monster",
	"Sentry Ooze",
	"Hivenest Monster",
	"Essence Reaver",
	"Quorbound Creature",
	"Quorbred Creature",
	"Du'ulora Quori",
	"Hashalaq Quori",
	"Kalaraq Quori",
	"Aspect of Graz'zt",
	"Aspect of Obox-Ob",
	"Aspect of Yeenoghu",
	"Corrupted by the Abyss",
	"Dabus",
	"Cambion Demon",
	"Carnevus Demon",
	"Oculus Demon",
	"Envoy of Lolth",
	"Abyssal Giant",
	"Lamia Noble",
	"Mirror Mephit",
	"Ratatosk",
	"Elder Viper Tree",
	"Adamantine Spider",
	"Chwidencha",
	"Draegloth",
	"Deep Dragon",
	"Albino Drow  Elf",
	"Bugbear Goblinoid",
	"Vril Goblinoid",
	"Husk Vermin",
	"Kuo-Toa",
	"Giant Lizard",
	"Footpad Lizard",
	"Quicksilver Lizard",
	"Subterranean Lizard",
	"Quaggoth",
	"Shunned",
	"Monstrous Spider",
	"Spitting Spider",
	"Tangle Terror",
	"Widowmaker",
	"Troll",
	"Venom Ooze",
	"Arcane Ballista",
	"Karrnathi Dread Marshal",
	"Mistling",
	"Umbral Spy",
	"Warforged Raptor",
	"Eyeball Swarm Beholderkin",
	"Myconid Venom Spore",
	"Snake Head",
	"Beast of Bane",
	"Fire Spider Swarm",
	"Shadow Simulacrum",
	"Shadowslain",
	"Arcadian Avenger",
	"Banshrae",
	"Blackwing",
	"Burrow Root",
	"Dalmosh",
	"Deadborn Vulture",
	"Adaru",
	"Carnage Demon",
	"Draudnu",
	"Gadacro",
	"Solamith",
	"Demonthorn Mandrake",
	"Gulthir",
	"Remmanon",
	"Stitched Devil",
	"Dragon of the Great Game",
	"Xorvintaal Dragon",
	"Xorvintaal Exarch",
	"Ken-Kuni",
	"Ken-Li",
	"Ken-Sun",
	"Ember Guard",
	"Ethereal Defiler",
	"Fetid Fungus",
	"Frostwind Virago",
	"Garngrath",
	"Gem Scarab",
	"God-Blooded Creature",
	"Force Golem",
	"Magmacore Golem",
	"Graveyard Sludge",
	"Greenspawn Zealot",
	"Guulvorg",
	"Bridge Haunt",
	"Forest Haunt",
	"Taunting Haunt",
	"Hobgoblin Duskblade",
	"Hobgoblin Spellscourge",
	"Hobgoblin Warcaster",
	"Hobgoblin Warsoul",
	"Illurien",
	"Jaebrin",
	"Crazed Kuo-Toa",
	"Kuo-Toa Exalted Whip",
	"Kuo-Toa Harpooner",
	"Kuo-Toa Monitor",
	"Malastor",
	"Merchurion",
	"Thoon Disciple",
	"Shadow Flayer",
	"Thoon Infiltrator",
	"Thoon Thrall",
	"Thoon Soldier",
	"Madcrafter of Thoon",
	"Scyther of Thoon",
	"Stormcloud of Thoon",
	"Thoon Hulk",
	"Thoon Elder Brain",
	"Mockery Monarch",
	"Mockery Drone",
	"Phantom",
	"Ruin Chanter",
	"Ruin Elemental",
	"Rylkar Harridan",
	"Rylkar Madclaw",
	"Rylkar Tormentor",
	"Rylkspawn Swarm",
	"Sanguineous Drinker",
	"Scouring Slinger",
	"Slinger Scorpion",
	"Scouring Stanchion",
	"Shaedling",
	"Shardsoul Slayer",
	"Siege Beetle",
	"Skull Lord",
	"Bonespur",
	"Serpentir",
	"Spectral Rider",
	"Lesser Spawn of Juiblex",
	"Greater Spawn of Juiblex",
	"Elder Spawn of Juiblex",
	"Spirrax",
	"Steelwing",
	"Thrym Hound",
	"Tirbana Eyewing",
	"Tirbana Drowser",
	"Tirbana Slayer",
	"Tirbana Spawner",
	"Bladerager Troll",
	"Tusk Terror",
	"Arkamoi",
	"Hadrimoi",
	"Lashemoi",
	"Turlemoi",
	"Verdant Reaver",
	"Vine Spawn",
	"Vivisector",
	"Master of the Hunt",
	"Hound of the Hunt",
	"Aurumvorax",
	"Cataboligne Demon",
	"Krinth",
	"Shadow Sea Serpent",
	"Sharn",
	"Veserab"
};
